project_id = "lojvajnnvhatfplevyvy"

[functions.resolve-couple-problem]
verify_jwt = false

[functions.get-client-ip]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.admin-reviews]
verify_jwt = false

[functions.admin-blog]
verify_jwt = false

[functions.blog-og]
verify_jwt = false

[functions.manage-ado-session]
verify_jwt = false

[functions.annuaire-profile]
verify_jwt = false

[functions.annuaire-stats]
verify_jwt = false

[functions.annuaire-track]
verify_jwt = false

[functions.contact-message]
verify_jwt = false

[functions.search-activities]
verify_jwt = false

[functions.admin-leads]
verify_jwt = false

[functions.admin-messages]
verify_jwt = false

[functions.trigger-deploy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.admin-annuaire]
verify_jwt = false

[functions.verify-annuaire-admin]
verify_jwt = false

[functions.ebook-verify]
verify_jwt = false

[functions.annuaire-stripe-webhook]
verify_jwt = false

[functions.annuaire-checkout]
verify_jwt = false

[functions.annuaire-generate-invoice]
verify_jwt = false

[functions.annuaire-billing-portal]
verify_jwt = false